# Change these first
owner: senthilkrea # Your GitHub organization or username, where this repository lives
repo: ping # The name of this repository

sites:
  - name: Krea Main Site
    url: https://krea.edu.in
  - name: Krea Erp
    url: https://erp-testing.krea.edu.in
  - name: Krea Cdn
    url: https://cdn.krea.edu.in
  - name: Krea Sis
    url: https://sis.krea.edu.in
  - name: Krea Budget
    url: http://budget.krea.edu.in
status-website:
  cname: status.krea.edu.in
  logoUrl: https://cdn.krea.edu.in/_/erp/logo.png
  name: Krea Status Page
  introTitle: "**Krea Status** is to maintain Krea Application Uptime."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Krea
      href: https://krea.edu.in

