# Change these first
owner: senthilkrea # Your GitHub organization or username, where this repository lives
repo: ping # The name of this repository

sites:
  - name: Krea Main Site
    url: https://krea.edu.in
  - name: Krea Erp
    url: https://erp-testing.krea.edu.in
  - name: Krea Cdn
    url: https://cdn.krea.edu.in
  - name: Krea Sis
    url: https://sis.krea.edu.in
  - name: Krea Budget
    url: http://budget.krea.edu.in
  - name: Aws Server
    url: https://aws-testing.krea.edu.in
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.krea.edu.in
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.krea.edu.in/_/erp/logo.png
  name: Krea Status Page
  introTitle: "**Krea Status** is to maintain Krea Application Uptime."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Krea
      href: https://krea.edu.in

